import { CustomizationEntry } from "../../Redux/reduxState";
import { Category, UISelectorType } from "../../utilities/types";

export const customizationEntries: CustomizationEntry[] = [
    {
        id: 'accent',
        displayName: 'Accent',
        category: Category.ColorAndPaddings,
        uiSelectorType: UISelectorType.colorSelector,
      },
      {
        id: 'backgroundColor',
        displayName: 'Background Color',
        category: Category.ColorAndPaddings,
        uiSelectorType: UISelectorType.colorSelector,
      },
      {
        id: 'cardEmphasisBackgroundColor',
        displayName: 'Card',
        category: Category.ColorAndPaddings,
        uiSelectorType: UISelectorType.colorSelector,
      },
      {
        id: 'userAvatarInitials',
        displayName: 'User Avatar Initials',
        category: Category.ColorAndPaddings,
        uiSelectorType: UISelectorType.integerSelector,
      },
      
        { id: 'cardEmphasisBackgroundColor',        
        displayName: 'Card Emphasis Background Color',
        category: Category.ColorAndPaddings,
        uiSelectorType: UISelectorType.colorSelector,
      },
      { id: 'paddingRegular',        
        displayName: 'Padding Regular',
        category: Category.ColorAndPaddings,
        uiSelectorType: UISelectorType.integerSelector,
      },
      { id: 'paddingWidth',        
        displayName: 'Padding Width',
        category: Category.ColorAndPaddings,
        uiSelectorType: UISelectorType.integerSelector,
      },
      { id: 'subtle'  ,      
        displayName: 'Subtle'  ,      
        category: Category.ColorAndPaddings,
        uiSelectorType: UISelectorType.colorSelector,
      },

      { id: 'fontSizeSmall',        
        displayName: 'Font Size Small',        
        category: Category.Fonts,
        uiSelectorType: UISelectorType.percentageSelector,
      },
      { id: 'monospaceFont',        
        displayName: 'Monospace Font',        
        category: Category.Fonts,
        uiSelectorType: UISelectorType.dropDownSelector,
      },
      { id: 'primaryFont',        
        displayName: 'Primary Font',        
        category: Category.Fonts,
        uiSelectorType: UISelectorType.dropDownSelector,
      },
      { id: 'messageActivityWordBreak',        
        displayName: 'Message Activity Word Break',        
        category: Category.Fonts,
        uiSelectorType: UISelectorType.defaultSelector,
      },
      { id: 'avatarBorderRadius',        
        displayName: 'Avatar Border Radius',        
        category: Category.Avatar,
        uiSelectorType: UISelectorType.percentageSelector,
      },
      { id: 'avatarSize',        
        displayName: 'Avatar Size',        
        category: Category.Avatar,
        uiSelectorType: UISelectorType.integerSelector,
      },
      { id: 'botAvatarBackgroundColor',        
        displayName: 'Bot Avatar Background Color',        
        category: Category.Avatar,
        uiSelectorType: UISelectorType.colorSelector,
      },
      { id: 'botAvatarImage',        
        displayName: 'Bot Avatar Image',        
        category: Category.Avatar,
        uiSelectorType: UISelectorType.defaultSelector,
      },
      { id: 'botAvatarInitials',        
        displayName: 'Bot Avatar Initials',        
        category: Category.Avatar,
        uiSelectorType: UISelectorType.defaultSelector,
      },
      { id: 'userAvatarBackgroundColor',        
        displayName: 'User Avatar Background Color',        
        category: Category.Avatar,
        uiSelectorType: UISelectorType.colorSelector,
      },
      { id: 'userAvatarImage',        
        displayName: 'User Avatar Image',        
        category: Category.Avatar,
        uiSelectorType: UISelectorType.defaultSelector,
      },
      { id: 'userAvatarInitials',        
        displayName: 'userAvatarInitials',        
        category: Category.Avatar,
        uiSelectorType: UISelectorType.defaultSelector,
      },
      { id: 'showAvatarInGroup',        
        displayName: 'showAvatarInGroup',        
        category: Category.Avatar,
        uiSelectorType: UISelectorType.dropDownSelector,
      },
      { id: 'bubbleBackground',        
        displayName: 'Bubble Background',        
        category: Category.ChatBubble,
        uiSelectorType: UISelectorType.colorSelector,
      },
      { id: 'bubbleBorderColor',        
        displayName: 'Bubble Border Color',        
        category: Category.ChatBubble,
        uiSelectorType: UISelectorType.colorSelector,
      },
      { id: 'bubbleBorderRadius',        
        displayName: 'Bubble Border Radius',        
        category: Category.ChatBubble,
        uiSelectorType: UISelectorType.integerSelector,
      },
      { id: 'bubbleBorderStyle',        
        displayName: 'Bubble Border Style',        
        category: Category.ChatBubble,
        uiSelectorType: UISelectorType.dropDownSelector,
      },
      { id: 'bubbleBorderWidth',        
        displayName: 'Bubble Border Width',        
        category: Category.ChatBubble,
        uiSelectorType: UISelectorType.integerSelector,
      },
      { id: 'bubbleFromUserBackground',        
        displayName: 'Bubble From User Background',        
        category: Category.ChatBubble,
        uiSelectorType: UISelectorType.colorSelector,
      },
      { id: 'bubbleFromUserBorderColor',        
        displayName: 'Bubble FromUserBorderColor',        
        category: Category.ChatBubble,
        uiSelectorType: UISelectorType.colorSelector,
      },
      { id: 'bubbleFromUserBorderRadius',        
        displayName: 'Bubble FromUserBorderRadius',        
        category: Category.ChatBubble,
        uiSelectorType: UISelectorType.integerSelector,
      },
      { id: 'bubbleFromUserBorderStyle',        
        displayName: 'Bubble FromUserBorderStyle',        
        category: Category.ChatBubble,
        uiSelectorType: UISelectorType.dropDownSelector,
      },
      { id: 'bubbleFromUserBorderWidth',        
        displayName: 'Bubble From User Border Width',        
        category: Category.ChatBubble,
        uiSelectorType: UISelectorType.integerSelector,
      },
      { id: 'bubbleFromUserNubOffset',        
        displayName: 'Bubble From User Nub Offset',        
        category: Category.ChatBubble,
        uiSelectorType: UISelectorType.integerSelector,
      },
      { id: 'bubbleFromUserNubSize',        
        displayName: 'Bubble FromUserNubSize',        
        category: Category.ChatBubble,
        uiSelectorType: UISelectorType.integerSelector,
      },
      { id: 'bubbleFromUserTextColor',        
        displayName: 'Bubble From User Text Color',        
        category: Category.ChatBubble,
        uiSelectorType: UISelectorType.colorSelector,
      },
      { id: 'bubbleImageHeight',        
        displayName: 'Bubble Image Height',        
        category: Category.ChatBubble,
        uiSelectorType: UISelectorType.integerSelector,
      },
      { id: 'bubbleMaxWidth',        
        displayName: 'Bubble Max Width',        
        category: Category.ChatBubble,
        uiSelectorType: UISelectorType.integerSelector,
      },
      { id: 'bubbleMinHeight',        
        displayName: 'Bubble Min Height',        
        category: Category.ChatBubble,
        uiSelectorType: UISelectorType.integerSelector,
      },
      { id: 'bubbleMinWidth',        
        displayName: 'Bubble Min Width',        
        category: Category.ChatBubble,
        uiSelectorType: UISelectorType.integerSelector,
      },
      { id: 'bubbleNubOffset',        
        displayName: 'Bubble Nub Offset',        
        category: Category.ChatBubble,
        uiSelectorType: UISelectorType.integerSelector,
      },
      { id: 'bubbleNubSize',        
        displayName: 'Bubble Nub Size',        
        category: Category.ChatBubble,
        uiSelectorType: UISelectorType.integerSelector,
      },
      { id: 'bubbleTextColor',        
        displayName: 'Bubble Text Color',        
        category: Category.ChatBubble,
        uiSelectorType: UISelectorType.colorSelector,
      },
      { id: 'markdownRespectCRLF',        
        displayName: 'Markdown Respect CRLF',        
        category: Category.Markdown,
        uiSelectorType: UISelectorType.booleanSelector,
      },
      { id: 'richCardWrapTitle',        
        displayName: 'Rich Card Wrap Title',        
        category: Category.Miscellaneous,
        uiSelectorType: UISelectorType.booleanSelector,
      },
      { id: 'rootHeight',        
        displayName: 'Root Height',        
        category: Category.Miscellaneous,
        uiSelectorType: UISelectorType.percentageSelector,
      },
      { id: 'rootWidth',        
        displayName: 'Root Width',        
        category: Category.Miscellaneous,
        uiSelectorType: UISelectorType.percentageSelector,
      },
      { id: 'rootZIndex',        
        displayName: 'Root Index',        
        category: Category.Miscellaneous,
        uiSelectorType: UISelectorType.integerSelector,
      },
      { id: 'hideScrollToEndButton',        
        displayName: 'Hide Scroll To End Button',        
        category: Category.Miscellaneous,
        uiSelectorType: UISelectorType.booleanSelector,
      },
      { id: 'hideSendBox',        
        displayName: 'Hide Send Box',        
        category: Category.SendBox,
        uiSelectorType: UISelectorType.booleanSelector,
      },
      { id: 'hideUploadButton',        
        displayName: 'Hide Upload Button',        
        category: Category.SendBox,
        uiSelectorType: UISelectorType.booleanSelector,
      },
      { id: 'microphoneButtonColorOnDictate',        
        displayName: 'Microphone Button Color On Dictate',        
        category: Category.SendBox,
        uiSelectorType: UISelectorType.colorSelector,
      },
      { id: 'sendBoxBackground',        
        displayName: 'Send Box Background',        
        category: Category.SendBox,
        uiSelectorType: UISelectorType.colorSelector,
      },
      { id: 'sendBoxButtonColor',        
        displayName: 'Send Box Button Color',        
        category: Category.SendBox,
        uiSelectorType: UISelectorType.colorSelector,
      },
      { id: 'sendBoxButtonColorOnDisabled',        
        displayName: 'Send Box Button Color On Disabled',        
        category: Category.SendBox,
        uiSelectorType: UISelectorType.colorSelector,
      },
      { id: 'sendBoxButtonColorOnFocus',        
        displayName: 'Send Box Button Color On Focus',        
        category: Category.SendBox,
        uiSelectorType: UISelectorType.colorSelector,
      },
      { id: 'sendBoxButtonColorOnHover',        
        displayName: 'Send Box Button Color On Hover',        
        category: Category.SendBox,
        uiSelectorType: UISelectorType.colorSelector,
      },
      { id: 'sendBoxDisabledTextColor',        
        displayName: 'Send Box Disabled Text Color',        
        category: Category.SendBox,
        uiSelectorType: UISelectorType.colorSelector,
      },
      { id: 'sendBoxHeight',        
        displayName: 'Send Box Height',        
        category: Category.SendBox,
        uiSelectorType: UISelectorType.integerSelector,
      },
      { id: 'sendBoxMaxHeight',        
        displayName: 'Send Box Max Height',        
        category: Category.SendBox,
        uiSelectorType: UISelectorType.integerSelector,
      },
      { id: 'sendBoxTextColor',        
        displayName: 'Send Box Text Color',        
        category: Category.SendBox,
        uiSelectorType: UISelectorType.colorSelector,
      },
      { id: 'sendBoxBorderBottom',        
        displayName: 'Send Box Border Bottom',        
        category: Category.SendBox,
        uiSelectorType: UISelectorType.defaultSelector,
      },
      { id: 'sendBoxBorderLeft',        
        displayName: 'Send Box Border Left',        
        category: Category.SendBox,
        uiSelectorType: UISelectorType.defaultSelector,
      },
      { id: 'sendBoxBorderRight',        
        displayName: 'Send Box Border Right',        
        category: Category.SendBox,
        uiSelectorType: UISelectorType.defaultSelector,
      },
      { id: 'sendBoxBorderTop',        
        displayName: 'Send Box Border Top',        
        category: Category.SendBox,
        uiSelectorType: UISelectorType.defaultSelector,
      },
      { id: 'sendBoxPlaceholderColor',        
        displayName: 'Send Box Placeholder Color',        
        category: Category.SendBox,
        uiSelectorType: UISelectorType.colorSelector,
      },
      { id: 'sendBoxTextWrap',        
        displayName: 'Send Box Text Wrap',        
        category: Category.SendBox,
        uiSelectorType: UISelectorType.booleanSelector,
      },
      { id: 'showSpokenText',        
        displayName: 'Show Spoken Text',        
        category: Category.Miscellaneous,
        uiSelectorType: UISelectorType.booleanSelector,
      },
      {
        id: 'suggestedActionBackground',
        displayName: 'Background Color',
        category: Category.SuggestedActions,
        uiSelectorType: UISelectorType.colorSelector,
      },
      {
        id: 'suggestedActionBorder',
        displayName: 'Border',
        category: Category.SuggestedActions,
        uiSelectorType: UISelectorType.defaultSelector,
      },
      {
        id: 'suggestedActionColor',
        displayName: 'Border Color',
        category: Category.SuggestedActions,
        uiSelectorType: UISelectorType.colorSelector,
      },
      {
        id: 'suggestedActionRadius',
        displayName: 'Border Radius',
        category: Category.SuggestedActions,
        uiSelectorType: UISelectorType.integerSelector,
      },
      {
        id: 'suggestedActionStyle',
        displayName: 'Border Style',
        category: Category.SuggestedActions,
        uiSelectorType: UISelectorType.dropDownSelector,
      },
      {
        id: 'suggestedActionWidth',
        displayName: 'Border Width',
        category: Category.SuggestedActions,
        uiSelectorType: UISelectorType.integerSelector,
      },
      {
        id: 'suggestedActionDisabledBackground',
        displayName: 'Background Color (Disabled)',
        category: Category.SuggestedActions,
        uiSelectorType: UISelectorType.colorSelector,
      },
      {
        id: 'suggestedActionDisabledTextColor',
        displayName: 'Text Color (Disabled)',
        category: Category.SuggestedActions,
        uiSelectorType: UISelectorType.colorSelector,
      },
      {
        id: 'suggestedActionDisabledBorder',
        displayName: 'Border (Disabled)',
        category: Category.SuggestedActions,
        uiSelectorType: UISelectorType.defaultSelector,
      },
      {
        id: 'suggestedActionDisabledColor',
        displayName: 'Border Color (Disabled)',
        category: Category.SuggestedActions,
        uiSelectorType: UISelectorType.colorSelector,
      },
      {
        id: 'suggestedActionDisabledRadius',
        displayName: 'Border Radius (Disabled)',
        category: Category.SuggestedActions,
        uiSelectorType: UISelectorType.integerSelector,
      },
      {
        id: 'suggestedActionDisabledStyle',
        displayName: 'Border Style (Disabled)',
        category: Category.SuggestedActions,
        uiSelectorType: UISelectorType.dropDownSelector,
      },
      {
        id: 'suggestedActionDisabledWidth',
        displayName: 'Border Width (Disabled)',
        category: Category.SuggestedActions,
        uiSelectorType: UISelectorType.integerSelector,
      },
      {
        id: 'suggestedActionHeight',
        displayName: 'Height',
        category: Category.SuggestedActions,
        uiSelectorType: UISelectorType.integerSelector,
      },
      {
        id: 'suggestedActionImageHeight',
        displayName: 'Image Height',
        category: Category.SuggestedActions,
        uiSelectorType: UISelectorType.integerSelector,
      },
      {
        id: 'suggestedActionLayout',
        displayName: 'Image Height',
        category: Category.SuggestedActions,
        uiSelectorType: UISelectorType.dropDownSelector,
      },
      {
        id: 'suggestedActionsCarouselFlipperCursor',
        displayName: 'Carousel Flipper Cursor',
        category: Category.SuggestedActions,
        uiSelectorType: UISelectorType.defaultSelector,
      },
      {
        id: 'suggestedActionsCarouselFlipperBoxWidth',
        displayName: 'Carousel Flipper Box Width',
        category: Category.SuggestedActions,
        uiSelectorType: UISelectorType.integerSelector,
      },
      {
        id: 'suggestedActionsCarouselFlipperSize',
        displayName: 'Carousel Flipper Size',
        category: Category.SuggestedActions,
        uiSelectorType: UISelectorType.integerSelector,
      },
      {
        id: 'suggestedActionsStackedHeight',
        displayName: "Container's Max Height",
        category: Category.SuggestedActions,
        uiSelectorType: UISelectorType.integerSelector,
      },
      {
        id: 'suggestedActionsStackedOverflow',
        displayName: "Container's Overflow Setting",
        category: Category.SuggestedActions,
        uiSelectorType: UISelectorType.dropDownSelector,
      },
      {
        id: 'groupTimestamp',
        displayName: "Group Timestamp",
        category: Category.Timestamp,
        uiSelectorType: UISelectorType.dropDownSelector,
      },
      {
        id: 'sendTimeout',
        displayName: "Send Timeout",
        category: Category.Timestamp,
        uiSelectorType: UISelectorType.integerSelector,
      },
      {
        id: 'sendTimeoutForAttachments',
        displayName: "Send Timeout for Attachments",
        category: Category.Timestamp,
        uiSelectorType: UISelectorType.integerSelector,
      },
      {
        id: 'timestampColor',
        displayName: "Color",
        category: Category.Timestamp,
        uiSelectorType: UISelectorType.colorSelector,
      },
      {
        id: 'timestampFormat',
        displayName: "Format",
        category: Category.Timestamp,
        uiSelectorType: UISelectorType.dropDownSelector,
      },
      {
        id: 'newMessagesButtonFontSize',
        displayName: "New Message Button Font Size",
        category: Category.TranscriptOverlayButtons,
        uiSelectorType: UISelectorType.percentageSelector,
      },
      {
        id: 'transcriptOverlayButtonColor',
        displayName: "Button Color",
        category: Category.TranscriptOverlayButtons,
        uiSelectorType: UISelectorType.colorSelector,
      },
      {
        id: 'transcriptOverlayButtonBackground',
        displayName: "Button Background Color",
        category: Category.TranscriptOverlayButtons,
        uiSelectorType: UISelectorType.rbgaSelector,
      },
      {
        id: 'transcriptOverlayButtonColorOnFocus',
        displayName: "Button Color: On Focus",
        category: Category.TranscriptOverlayButtons,
        uiSelectorType: UISelectorType.rbgaSelector,
      },
      {
        id: 'transcriptOverlayButtonBackgroundOnFocus',
        displayName: "Button Background Color: On Focus",
        category: Category.TranscriptOverlayButtons,
        uiSelectorType: UISelectorType.rbgaSelector,
      },
      {
        id: 'transcriptOverlayButtonColorOnHover',
        displayName: "Button Color: On Hover",
        category: Category.TranscriptOverlayButtons,
        uiSelectorType: UISelectorType.rbgaSelector,
      },
      {
        id: 'transcriptOverlayButtonBackgroundOnHover',
        displayName: "Button Background Color: On Hover",
        category: Category.TranscriptOverlayButtons,
        uiSelectorType: UISelectorType.rbgaSelector,
      },
      {
        id: 'videoHeight',
        displayName: "Video Height",
        category: Category.Miscellaneous,
        uiSelectorType: UISelectorType.integerSelector,
      },
      {
        id: 'connectivityIconPadding',
        displayName: "Icon Padding",
        category: Category.ConnectivityUI,
        uiSelectorType: UISelectorType.integerSelector,
      },
      {
        id: 'connectivityMarginLeftRight',
        displayName: "Margin - Left and Right",
        category: Category.ConnectivityUI,
        uiSelectorType: UISelectorType.integerSelector,
      },
      {
        id: 'connectivityMarginTopBottom',
        displayName: "Margin - Top and Bottom",
        category: Category.ConnectivityUI,
        uiSelectorType: UISelectorType.integerSelector,
      },
      {
        id: 'connectivityTextSize',
        displayName: "Text Size",
        category: Category.ConnectivityUI,
        uiSelectorType: UISelectorType.percentageSelector,
      },
      {
        id: 'failedConnectivity',
        displayName: "Failed Connectivity Color",
        category: Category.ConnectivityUI,
        uiSelectorType: UISelectorType.colorSelector,
      },
      {
        id: 'slowConnectivity',
        displayName: "Slow Connectivity Color",
        category: Category.ConnectivityUI,
        uiSelectorType: UISelectorType.colorSelector,
      },
      {
        id: 'notificationText',
        displayName: "Notification Text Color",
        category: Category.ConnectivityUI,
        uiSelectorType: UISelectorType.colorSelector,
      },
      {
        id: 'slowConnectionAfter',
        displayName: "Slow Connection After",
        category: Category.ConnectivityUI,
        uiSelectorType: UISelectorType.integerSelector,
      },
      {
        id: 'typingAnimationBackgroundImage',
        displayName: "Typing Animation: Background Image (url)",
        category: Category.ConnectivityUI,
        uiSelectorType: UISelectorType.defaultSelector,
      },
      {
        id: 'typingAnimationDuration',
        displayName: "Typing Animation: Duration",
        category: Category.ConnectivityUI,
        uiSelectorType: UISelectorType.integerSelector,
      },
      {
        id: 'typingAnimationHeight',
        displayName: "Typing Animation: Height",
        category: Category.ConnectivityUI,
        uiSelectorType: UISelectorType.integerSelector,
      },
      {
        id: 'typingAnimationWidth',
        displayName: "Typing Animation: Width",
        category: Category.ConnectivityUI,
        uiSelectorType: UISelectorType.integerSelector,
      },
      {
        id: 'spinnerAnimationBackgroundImage',
        displayName: "Spinner Animation: Background Image (url)",
        category: Category.ConnectivityUI,
        uiSelectorType: UISelectorType.integerSelector,
      },
      {
        id: 'spinnerAnimationHeight',
        displayName: "Spinner Animation: Height",
        category: Category.ConnectivityUI,
        uiSelectorType: UISelectorType.integerSelector,
      },
      {
        id: 'spinnerAnimationWidth',
        displayName: "Spinner Animation: Width",
        category: Category.ConnectivityUI,
        uiSelectorType: UISelectorType.integerSelector,
      },
      {
        id: 'spinnerAnimationPadding',
        displayName: "Spinner Animation: Padding",
        category: Category.ConnectivityUI,
        uiSelectorType: UISelectorType.integerSelector,
      },
      {
        id: 'enableUploadThumbnail',
        displayName: "Upload Thumbnail: Enable",
        category: Category.ConnectivityUI,
        uiSelectorType: UISelectorType.booleanSelector,
      },
      {
        id: 'uploadThumbnailContentType',
        displayName: "Upload Thumbnail: Type",
        category: Category.ConnectivityUI,
        uiSelectorType: UISelectorType.dropDownSelector,
      },
      {
        id: 'uploadThumbnailHeight',
        displayName: "Upload Thumbnail: Height",
        category: Category.ConnectivityUI,
        uiSelectorType: UISelectorType.integerSelector,
      },
      {
        id: 'uploadThumbnailWidth',
        displayName: "Upload Thumbnail: Width",
        category: Category.ConnectivityUI,
        uiSelectorType: UISelectorType.integerSelector,
      },
      {
        id: 'uploadThumbnailQuality',
        displayName: "Upload Thumbnail: Quality",
        category: Category.ConnectivityUI,
        uiSelectorType: UISelectorType.defaultSelector,
      },
      {
        id: 'notificationDebounceTimeout',
        displayName: "Notification Debounce Timeout",
        category: Category.ToastUI,
        uiSelectorType: UISelectorType.integerSelector,
      },
      {
        id: 'hideToaster',
        displayName: "Hide Toaster",
        category: Category.ToastUI,
        uiSelectorType: UISelectorType.booleanSelector,
      },
      {
        id: 'toasterHeight',
        displayName: "Height",
        category: Category.ToastUI,
        uiSelectorType: UISelectorType.integerSelector,
      },
      {
        id: 'toasterMaxHeight',
        displayName: "Max Height",
        category: Category.ToastUI,
        uiSelectorType: UISelectorType.integerSelector,
      },
      {
        id: 'toasterSingularMaxHeight',
        displayName: "Singular Max Height",
        category: Category.ToastUI,
        uiSelectorType: UISelectorType.integerSelector,
      },
      {
        id: 'toastFontSize',
        displayName: "Font Size",
        category: Category.ToastUI,
        uiSelectorType: UISelectorType.percentageSelector,
      },
      {
        id: 'toastIconWidth',
        displayName: "Icon Width",
        category: Category.ToastUI,
        uiSelectorType: UISelectorType.integerSelector,
      },
      {
        id: 'toastSeparatorColor',
        displayName: "Separator Color",
        category: Category.ToastUI,
        uiSelectorType: UISelectorType.colorSelector,
      },
      {
        id: 'toastTextPadding',
        displayName: "Text Padding",
        category: Category.ToastUI,
        uiSelectorType: UISelectorType.integerSelector,
      },
      {
        id: 'toastTextPadding',
        displayName: "Text Padding",
        category: Category.ToastUI,
        uiSelectorType: UISelectorType.integerSelector,
      },
      {
        id: 'toastErrorColor',
        displayName: "Error Color",
        category: Category.ToastUI,
        uiSelectorType: UISelectorType.colorSelector,
      },
      {
        id: 'toastErrorBackgroundColor',
        displayName: "Error Background Color",
        category: Category.ToastUI,
        uiSelectorType: UISelectorType.colorSelector,
      },
      {
        id: 'toastInfoColor',
        displayName: "Info Color",
        category: Category.ToastUI,
        uiSelectorType: UISelectorType.colorSelector,
      },
      {
        id: 'toastInfoBackgroundColor',
        displayName: "Info Background Color",
        category: Category.ToastUI,
        uiSelectorType: UISelectorType.colorSelector,
      },
      {
        id: 'toastSuccessColor',
        displayName: "Success Color",
        category: Category.ToastUI,
        uiSelectorType: UISelectorType.colorSelector,
      },
      {
        id: 'toastSuccessBackgroundColor',
        displayName: "Success Background Color",
        category: Category.ToastUI,
        uiSelectorType: UISelectorType.colorSelector,
      },
      {
        id: 'toastWarnColor',
        displayName: "Warn Color",
        category: Category.ToastUI,
        uiSelectorType: UISelectorType.colorSelector,
      },
      {
        id: 'toastWarnBackgroundColor',
        displayName: "Warn Background Color",
        category: Category.ToastUI,
        uiSelectorType: UISelectorType.colorSelector,
      },
      {
        id: 'emojiSet',
        displayName: "Emoji Set",
        category: Category.Miscellaneous,
        uiSelectorType: UISelectorType.defaultSelector,
      },
];
