export enum Category {
    // The order of this enum will effect
    // the order they render on the webapp
    ColorAndPaddings = 'Color & Paddings',
    Fonts = 'Fonts',
    ChatBubble = 'Chat Bubble',
    Avatar = 'Avatar',
    ConnectivityUI = 'Connectivity UI',
    SendBox = 'Send Box',
    SuggestedActions = 'Suggested Actions',
    Timestamp = 'Timestamp',
    ToastUI = 'Toast UI',
    TranscriptOverlayButtons = 'Transcript Overlay Buttons',
    Miscellaneous = 'Miscellaneous',
}

export enum SubCategory {
    AvatarChatBubble = 'Avatar Chat Bubble',
    AvatarSettings = 'Avatar Settings',
    BotAvatar = 'Bot Avatar',
    Border = 'Border',
    BorderDisabled = 'Border (Disabled)',
    ButtonColors = 'Button Colors',
    ButtonDefault = 'Button: Default',
    ButtonOnFocus = 'Button: On Focus',
    ButtonOnHover = 'Button: On Hover',
    CarouselFlipper = 'Carousel Flipper',
    Colors = 'Colors',
    ConnectivityStyling = 'Connectivity Styling',
    Container = 'Container',
    Error = 'Error',
    Info = 'Info',
    Layout = 'Layout',
    NotificationTimeout = 'Notification Timeout',
    SlowConnectionTimeOut = 'Slow Connection Timeout',
    SpinnerAnimation = 'Spinner Animation',
    Success = 'Success',
    ToasterLayout = 'Toaster Layout',
    ToasterStyling = 'Toaster Styling',
    TypingAnimation = 'Typing Animation',
    UploadThumbnail = 'Upload Thumbnail',
    UserAvatar = 'User Avatar',
    UserChatBubble = 'User Chat Bubble',
    Warn = 'Warn',
}

export enum UISelectorType {
    booleanSelector = 'booleanSelector',
    colorSelector = 'colorSelector',
    defaultSelector = 'defaultSelector',
    dropDownSelector = 'dropDownSelector',
    integerSelector = 'integerSelector',
    percentageSelector = 'percentageSelector',
    rbgaSelector = 'rbgaSelector',
}
